package models

import (
	"errors"
	"fmt"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	"gitlab.com/michellejae/lenslocked.com/hash"
	"gitlab.com/michellejae/lenslocked.com/rand"
	"golang.org/x/crypto/bcrypt"
)

var (
	// return when a resource cannot be found in DB
	ErrNotFound = errors.New("models: resource not found")

	// returned when an invalid id is provided to a mehod like delete
	ErrInvalidID = errors.New("models: id provided was invalid")
	// return when authentenicate gets incorrect password
	ErrInvalidPassword = errors.New("models: incorrect password provided")
)

const userPwPepper = "booopity-beep-berp"
const hmacSecretKey = "secret-hmac-key"

//userDB is used to interact with the usrs database

// If the user is found, we will return a nil error
// If the user is not found, we will return ErrNotFound
//If there is another error, we will return an error with more information
// about what went wrong. This may not be an error generated by the model package

// for single user queries, as a general rule, any error but ErrNotFound should probaly result in a 500 error

type UserDB interface {
	// methodd for querying or single Users
	ByID(id uint) (*User, error)
	ByEmail(email string) (*User, error)
	ByRemember(token string) (*User, error)

	// methods for altering users
	Create(user *User) error
	Update(user *User) error
	Delete(id uint) error

	// used to close a DB connection
	Close() error

	//Migration Helpers
	AutoMigrate() error
	DestructiveReset() error
}

// user service now only handles authenticate
// accesses userGorm in order to acccess DB
func NewUserService(connectionInfo string) (*UserService, error) {
	ug, err := newUserGorm(connectionInfo)
	if err != nil {
		return nil, err
	}
	return &UserService{
		UserDB: &userValidator{
			UserDB: ug,
		},
	}, nil
}

// underscore tells compiler that this variable will never actually be used
// however setting UserDB to the userGorm ensures that the userGorm type always matches UserDB interface
var _ UserDB = &userGorm{}

// UserService type that will chain into UserDB interface
type UserService struct {
	UserDB
}

type userValidator struct {
	UserDB
}

// connects into DB and returns a userGorm type
// have to return this type as it has all the methods for interacting with DB
func newUserGorm(connectionInfo string) (*userGorm, error) {
	db, err := gorm.Open("postgres", connectionInfo)
	if err != nil {
		return nil, err
	}
	db.LogMode(true)
	hmac := hash.NewHmac(hmacSecretKey)
	return &userGorm{
		db:   db,
		hmac: hmac,
	}, nil
}

type userGorm struct {
	db   *gorm.DB
	hmac hash.HMAC
}

func (ug *userGorm) ByID(id uint) (*User, error) {
	var user User
	db := ug.db.Where("id = ?", id)
	err := first(db, &user)
	return &user, err
}

// same as above but byEMAIL
func (ug *userGorm) ByEmail(email string) (*User, error) {
	// this is the user where we play the return from the db
	var user User
	db := ug.db.Where("email = ?", email)
	err := first(db, &user)
	return &user, err
}

// looks up a user with the given remember token and retunr thats user
// this method will handle hashing the token for us
// errors are the same as byEmail
func (ug *userGorm) ByRemember(token string) (*User, error) {

	var user User
	rememberHash := ug.hmac.Hash(token)
	fmt.Println("HERERRE", rememberHash)
	// query has to use remember_hash even though we save it as RememberHash down below
	err := first(ug.db.Where("remember_hash = ?", rememberHash), &user)
	if err != nil {
		return nil, err
	}

	return &user, nil

}

// can be used to authenticate a user with the provided email address and password
// if the email provided is invalid this will return nil, ErrNotFound
// if the password provided is invalid this will return nil, ErrInvalidPassword
// if both are valid, will return user, nil
// if both are invalid will return nil, error

// we keep this as a userService method cause though we have to grab info from DB
// it's not really doing anything with DB. it's more about the USER
func (us *UserService) Authenticate(email, password string) (*User, error) {
	foundUser, err := us.ByEmail(email)
	if err != nil {
		return nil, err
	}

	err = bcrypt.CompareHashAndPassword([]byte(foundUser.PasswordHash), []byte(password+userPwPepper))
	if err != nil {
		switch err {
		case bcrypt.ErrMismatchedHashAndPassword:
			return nil, ErrInvalidPassword
		default:
			return nil, err
		}

	}
	return foundUser, nil
}

// first will query using provided gorm.db and will
// get first item return and place it into dst
// if nothing is return (or fround in query) it will return err not found
func first(db *gorm.DB, dst interface{}) error {
	err := db.First(dst).Error
	if err == gorm.ErrRecordNotFound {
		return ErrNotFound
	}
	return err
}

//Creat provided user and backfill data like the ID, CreatedAt and UpdatedAt fields
func (ug *userGorm) Create(user *User) error {
	pwBytes := []byte(user.Password + userPwPepper)
	hashedBytes, err := bcrypt.GenerateFromPassword(pwBytes, bcrypt.DefaultCost)
	if err != nil {
		return err
	}
	user.PasswordHash = string(hashedBytes)
	user.Password = ""

	if user.Remember == "" {
		token, err := rand.RememberToken()
		if err != nil {
			return err
		}
		user.Remember = token
	}

	user.RememberHash = ug.hmac.Hash(user.Remember)

	return ug.db.Create(user).Error
}

// will update the provied user with the provided user object
// note that you ahve to provide ALL fields whether their data is updatd or not
// ie if the email is staying the same and you don't provide it, it will delete
func (ug *userGorm) Update(user *User) error {
	if user.Remember != "" {
		user.RememberHash = ug.hmac.Hash(user.Remember)
	}
	return ug.db.Save(user).Error
}

// will delete the user with the provided ID
func (ug *userGorm) Delete(id uint) error {
	if id == 0 {
		return ErrInvalidID
	}

	// have to actually specify model to get acces to gorm.Model to get the ID
	user := User{Model: gorm.Model{ID: id}}
	return ug.db.Delete(&user).Error
}

// closes the UserService DB connection
func (ug *userGorm) Close() error {
	return ug.db.Close()
}

// method only used in development to reset database just to make sure we are starting fresh
// drops user table and rebuilds it
func (ug *userGorm) DestructiveReset() error {
	if err := ug.db.DropTableIfExists(&User{}).Error; err != nil {
		return err
	}
	return ug.AutoMigrate()

}

// Automigrate will attempt to automatiaclly migrate the users table
func (ug *userGorm) AutoMigrate() error {
	if err := ug.db.AutoMigrate(&User{}).Error; err != nil {
		return err
	}
	return nil
}

type User struct {
	gorm.Model
	Name         string
	Email        string `gorm:"not null;unique_index"`
	Password     string `gorm:"-"` //- means ignore this and don't store in db
	PasswordHash string `gorm:"not null"`
	Remember     string `gorm:"-"`
	RememberHash string `gorm:"not null;unique_index"`
}
